#!/usr/bin/env python3
"""LINGO-025 bug fix: formatAspectLine's pairKind='none'-with-aspectPair branch
composes `対なし・常に<体>）。関連: <pair>（<pairNote>）` — the "関連: <pair>"
scaffolding is now generated by the UI code, so pair_note must be ONLY the
short clarifying gloss (e.g. "しばらく横になる"), not a full restatement like
"状態動詞、対の完了体なし。関連: полежать（しばらく横になる）" (which was the
pre-LINGO-025 authoring style and, left in place, renders as visibly
duplicated text — caught by rendering лежать and checking the actual output
string before shipping).

Rewrites the pair_note for every pair_kind="none" row that has a non-null
aspect_pair, in both manual_overrides.json and the aspect_batches source
files (so build_aspects.py remains the single reproducible assembly step).
"""
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

CLEAN_NOTES = {
    "работать": "少し働く",
    "жить": "しばらく暮らす／прожить=〜年生きる（期間）",
    "спать": "少し眠る。「眠りに落ちる」はуснуть⇔засыпать（別動詞）",
    "надеяться": "少し期待する・あてにする",
    "держать": "少し持つ",
    "сидеть": "少し座る。別動詞: садиться→сесть（座る動作そのもの）",
    "беспокоиться": "しばらく心配する",
    "стоять": "少し立つ",
    "существовать": "〜の間存在した",
    "лежать": "しばらく横になる／参考: ложиться–лечь（横になる動作）",
    "переживать": "しばらく心配する",
    "постоять": "стоятьの限定相（少し立つ）",
    "судить": "しばらく判断・考察する",
    "дышать": "少し呼吸する",
    "бороться": "少し闘う",
    "гордиться": "しばらく誇らしく思う",
    "управлять": "しばらく管理・運転する",
    "мечтать": "少し夢想する",
    "молчать": "しばらく黙る",
    "участвовать": "一定時間・一度参加する",
    "общаться": "しばらく交流・会話する",
    "преследовать": "しばらく追う",
    "сражаться": "しばらく戦う",
    "служить": "一定期間仕える",
    "курить": "しばらく吸う",
    "путешествовать": "しばらく旅行する",
    "побыть": "бытьの限定相（しばらくいる）",
    "поработать": "работатьの限定相（少し働く）",
    "нервничать": "しばらく緊張・心配する",
    "поиграть": "少し遊ぶ",
    "охотиться": "しばらく狩りをする",
    "поискать": "искатьの限定相（少し探す）。искать自体の対はнайти",
    "посидеть": "сидетьの限定相（少し座る）",
    "поспать": "спатьの限定相（少し眠る）",
    "потерпеть": "少し我慢する",
    "веселиться": "少し楽しむ",
    "повеселиться": "веселитьсяの限定相（少し楽しく過ごす）",
    "присутствовать": "しばらく出席する",
    "биться": "しばらく戦う。心臓の鼓動には完了体なし",
    "завидовать": "一時的に羨む",
    "подержать": "держатьの限定相（少し持つ）",
    "висеть": "しばらく掛かっている",
    "воевать": "しばらく戦う（限界相）",
}


def fix_dict(d, changed_counter):
    for lemma, note in CLEAN_NOTES.items():
        if lemma in d and d[lemma].get("pair_kind") == "none" and d[lemma].get("aspect_pair"):
            if d[lemma]["pair_note"] != note:
                d[lemma]["pair_note"] = note
                changed_counter[0] += 1


def main():
    changed = [0]

    ov_path = os.path.join(HERE, "manual_overrides.json")
    with open(ov_path, encoding="utf-8") as f:
        overrides = json.load(f)
    fix_dict(overrides, changed)
    with open(ov_path, "w", encoding="utf-8") as f:
        json.dump(overrides, f, ensure_ascii=False, indent=2)

    for path in sorted(glob.glob(os.path.join(HERE, "aspect_batches", "out_*.json"))):
        with open(path, encoding="utf-8") as f:
            rows = json.load(f)
        by_lemma = {r["lemma"]: r for r in rows}
        before = changed[0]
        fix_dict(by_lemma, changed)
        if changed[0] != before:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(rows, f, ensure_ascii=False, indent=1)

    print(f"cleaned {changed[0]} pair_note fields ({len(CLEAN_NOTES)} target lemmas)")


if __name__ == "__main__":
    main()
